version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rg_daemon
permissions:
  - object: "/home/ec2-user/rg_daemon"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      runas: ec2-user


