version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rg_daemon
permissions:
  - object: "/home/ec2-user/rg_daemon"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root



