version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: "/home/ec2-user"
    owner: ec2-use
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      runas: ec2-user


