#!/bin/bash
yum install -y httpd
deploymentid= $(aws deploy get-deployment-group --application-name nht --deployment-group-name nht-ec2 --query deploymentGroupInfo.deploymentGroupId --output text)
sudo echo /var/www/html/index.html >> /opt/codedeploy-agent/deployment-root/deployment-instructions/$deploymentid-cleanup
#yum install -y git
